### ISSUE TITLE
Configure Spring Boot Security to use OAuth 2.0

### ISSUE THREAD

**Issue by bartlomiejkrawczyk** [ERSMS-24L/ERSMS-24L#43]
Here is an example how to configure oauth2 with google identity provider: 
https://docs.spring.io/spring-security/reference/reactive/oauth2/login/core.html

And here is a document how we could use oauth2 along with gateway services:
https://www.baeldung.com/spring-cloud-gateway-oauth2

But I'm not sure if we need to use gateway service with authorization. If it's easier I would go for the same separate token verification in all of the services.

**Comment by ianczyko** [comment]
resolved in #102
