### ISSUE TITLE
Setup frontend repository

### ISSUE THREAD

**Issue by bartlomiejkrawczyk** [ERSMS-24L/ERSMS-24L#45]
We could either:
- use some framework to setup our web page (React, Angular or Vue)
- work without any js frameworks (I know @MKuranowski preferes this option, but we are open to any propositions)

@LeXmor15 Have you got any experience with web design and javascript development?

**Comment by LeXmor15** [comment]
I don't have any experience with web design (I had with WordPress but I don't think that's what we are looking for). Neither with Angular but I think I can learn, It may not be so hard, I hope.

**Comment by MKuranowski** [comment]
This was completed in #108 and #128.
