### ISSUE TITLE
Frontend - complete ui

### ISSUE THREAD

**Issue by bartlomiejkrawczyk** [ERSMS-24L/ERSMS-24L#73]
Main pages that actually need mockups:

- [x] Main page - paginated list of threads
- [x] Thread page - paginated list of posts
  - [x] Each post should have an associated edit button, only visible for the post's author
  - [x] Each post should have an associated delete post buttons, visible only for thread's moderators and post's author
  - [x] Each post should have an associated ban user thread-wide button, only visible for the thread's moderators
  - [x] Each post should have an associated ban user site-wide button, only visible for the administrators
- [x] Login page
- [x] Create thread page
- [x] Create post page
- [x] Thread management page - accessible from the thread page for moderators, where they can manage banned users and appoint/remove moderators
- [x] Global management page - where administrators can manage banned users

Think of a traditional forum, here are some examples:
- https://www.skyscrapercity.com/
- https://forum.paradoxplaza.com/forum/forums/cities-skylines.859/
![image](https://github.com/ERSMS-24L/ERSMS-24L/assets/16469272/16dcaf60-7fae-453a-8d09-26dc46f029e6)
![image](https://github.com/ERSMS-24L/ERSMS-24L/assets/16469272/76bbdcc1-6f07-476f-9f01-c1fad9054516)

**Comment by MKuranowski** [comment]
Main page was added in #128

**Comment by MKuranowski** [comment]
Basic thread view, create thread and create post pages added in #149

**Comment by MKuranowski** [comment]
Login more-or-less completed in #168

**Comment by MKuranowski** [comment]
Voting & editing added in #191

**Comment by MKuranowski** [comment]
Global management page, site wide ban user button - scrapped, will be handled through Keycloack UI

**Comment by MKuranowski** [comment]
User banning and thread management added in #205, this concludes the UI.
